# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74c721b8f0f08392920c73fe6ec8b8cf5567bdabf075e19ad63b5232a3ead25b2fd9ae1274231d5040191f279fd631778dd50d549d42902cafd80a3691490473

test:
  secret_key_base: 5230068175bca0fe891dada0795bf466db1aa2bfc09bbe825a0b0cc7ce6121463a8cc39d12fe216394afa9d4ab0fd1c35205fef3f526441b4d305f0bec3904bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
